#!/usr/bin/env bash
# Pings an IP address 5 times or displays usage if no argument is provided

if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    ping -c 5 "$1"
fi